sudo: required
services:
- docker
language: bash
script:
# build image
- docker build -t jaikuai/rpi-svn .
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker push jaikuai/rpi-svn
